# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install Java 
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
# Maven Package - create the function artifacts in
- task: Maven@2
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'apachefop-serverless-az-func/pom.xml'
# Copy files    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/azure-functions/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
# Create Archive : zip file
- task: ArchiveFiles@2
  displayName: 'Archive $(build.artifactstagingdirectory)/apachefop-serverless-az-func/target/azure-functions/apachefop-serverless-az-func'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/apachefop-serverless-az-func/target/azure-functions/apachefop-serverless-az-func'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
